package datastore

import (
	"testing"
	"time"

	"github.com/ernestrc/blue/rpc"
	"github.com/stretchr/testify/assert"
)

func makeRPCView() *rpc.View {
	now := stdTimeToProto(time.Now())
	return &rpc.View{
		Name:          str1,
		ProjectId:     str2,
		Query:         str1,
		Source:        str1,
		AutoGenerated: trueBool,
		Description:   str3,
		Schema:        str2,
		CreatedAt:     &now,
		UpdatedAt:     &now,
	}
}

func assertEqualViews(t *testing.T, expectedEnt, outputEnt Entity) {
	expected := expectedEnt.(*View)
	output := outputEnt.(*View)
	expected.UpdatedAt = time.Time{}
	expected.CreatedAt = time.Time{}
	output.UpdatedAt = time.Time{}
	output.CreatedAt = time.Time{}

	assert.Equal(t, expected, output)
}

func TestViewProtoConversion(t *testing.T) {
	rpcView := makeRPCView()
	testEntityProtoConversion(t, new(View), rpcView)
}

func TestViewPersistence(t *testing.T) {
	var inputView, outputView View
	rpcView := makeRPCView()
	inputView.FromProto(rpcView)
	testResourcePersistence(t, &inputView, &outputView, assertEqualViews)
}
