package datastore

import (
	"time"

	"github.com/ernestrc/blue/datastore/document"
	"github.com/ernestrc/blue/rpc"
	"github.com/golang/protobuf/proto"
)

// View represents a more idiomatic version of rpc.View.
// It satisfies datastore.Entity so it can be converted from/to rpc.View.
type View struct {
	ID          string
	Name        string
	ProjectID   string
	Description string

	Source        string
	Query         string
	Schema        string
	AutoGenerated bool

	UpdatedAt time.Time `firestore:",serverTimestamp"`
	CreatedAt time.Time `firestore:",serverTimestamp"`
}

// FromProto panics if msg is not a *rpc.View
func (s *View) FromProto(msg proto.Message) {
	view, ok := msg.(*rpc.View)
	if !ok {
		panic(ErrInvalidProtoMessage)
	}

	name := view.GetName()

	s.ProjectID = view.GetProjectId()
	s.ID = MakeDocumentID(s.ProjectID, name)
	s.Name = name
	s.Query = view.GetQuery()
	s.Source = view.GetSource()
	s.Schema = view.GetSchema()
	s.AutoGenerated = view.GetAutoGenerated()
	s.Description = view.GetDescription()
	s.CreatedAt = protoTimeToStd(view.GetCreatedAt())
	s.UpdatedAt = protoTimeToStd(view.GetUpdatedAt())
}

// ToProto converts s into *rpc.View
func (s *View) ToProto() proto.Message {
	createdAt := stdTimeToProto(s.CreatedAt)
	updatedAt := stdTimeToProto(s.UpdatedAt)

	return &rpc.View{
		Name:          s.Name,
		ProjectId:     s.ProjectID,
		Description:   s.Description,
		Query:         s.Query,
		Source:        s.Source,
		Schema:        s.Schema,
		AutoGenerated: s.AutoGenerated,
		CreatedAt:     &createdAt,
		UpdatedAt:     &updatedAt,
	}
}

// ToProtoResource converts s into a *rpc.Resource
func (s *View) ToProtoResource() *rpc.Resource {
	return &rpc.Resource{
		Resource: &rpc.Resource_View{
			View: s.ToProto().(*rpc.View),
		},
	}
}

// WithUpdateQuery returns an updated slice of updates
// which updates a document field `Query`.
func WithUpdateQuery(in []document.Update, query string) []document.Update {
	return append(in, document.Update{FieldPath: []string{"Query"}, Value: query})
}

// WithUpdateSource returns an updated slice of updates
// which updates a document field `Source`.
func WithUpdateSource(in []document.Update, source string) []document.Update {
	return append(in, document.Update{FieldPath: []string{"Source"}, Value: source})
}

// WithUpdateSchema returns an updated slice of updates
// which updates a document field `Schema`.
func WithUpdateSchema(in []document.Update, schema string) []document.Update {
	return append(in, document.Update{FieldPath: []string{"Schema"}, Value: schema})
}
