// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/datastore.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDocumentRequest) Reset()         { *m = CreateDocumentRequest{} }
func (m *CreateDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDocumentRequest) ProtoMessage()    {}
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{0}
}

func (m *CreateDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDocumentRequest.Unmarshal(m, b)
}
func (m *CreateDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDocumentRequest.Marshal(b, m, deterministic)
}
func (m *CreateDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDocumentRequest.Merge(m, src)
}
func (m *CreateDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDocumentRequest.Size(m)
}
func (m *CreateDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDocumentRequest proto.InternalMessageInfo

func (m *CreateDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateDocumentRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SetDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDocumentRequest) Reset()         { *m = SetDocumentRequest{} }
func (m *SetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*SetDocumentRequest) ProtoMessage()    {}
func (*SetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{1}
}

func (m *SetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDocumentRequest.Unmarshal(m, b)
}
func (m *SetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDocumentRequest.Marshal(b, m, deterministic)
}
func (m *SetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDocumentRequest.Merge(m, src)
}
func (m *SetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_SetDocumentRequest.Size(m)
}
func (m *SetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDocumentRequest proto.InternalMessageInfo

func (m *SetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetDocumentRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateDocumentRequest struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Updates              []*UpdateDocumentRequest_Update `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateDocumentRequest) Reset()         { *m = UpdateDocumentRequest{} }
func (m *UpdateDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDocumentRequest) ProtoMessage()    {}
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{2}
}

func (m *UpdateDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDocumentRequest.Unmarshal(m, b)
}
func (m *UpdateDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDocumentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDocumentRequest.Merge(m, src)
}
func (m *UpdateDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDocumentRequest.Size(m)
}
func (m *UpdateDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDocumentRequest proto.InternalMessageInfo

func (m *UpdateDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDocumentRequest) GetUpdates() []*UpdateDocumentRequest_Update {
	if m != nil {
		return m.Updates
	}
	return nil
}

type UpdateDocumentRequest_Update struct {
	FieldPath            []string `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDocumentRequest_Update) Reset()         { *m = UpdateDocumentRequest_Update{} }
func (m *UpdateDocumentRequest_Update) String() string { return proto.CompactTextString(m) }
func (*UpdateDocumentRequest_Update) ProtoMessage()    {}
func (*UpdateDocumentRequest_Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{2, 0}
}

func (m *UpdateDocumentRequest_Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDocumentRequest_Update.Unmarshal(m, b)
}
func (m *UpdateDocumentRequest_Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDocumentRequest_Update.Marshal(b, m, deterministic)
}
func (m *UpdateDocumentRequest_Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDocumentRequest_Update.Merge(m, src)
}
func (m *UpdateDocumentRequest_Update) XXX_Size() int {
	return xxx_messageInfo_UpdateDocumentRequest_Update.Size(m)
}
func (m *UpdateDocumentRequest_Update) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDocumentRequest_Update.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDocumentRequest_Update proto.InternalMessageInfo

func (m *UpdateDocumentRequest_Update) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *UpdateDocumentRequest_Update) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentRequest) Reset()         { *m = GetDocumentRequest{} }
func (m *GetDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentRequest) ProtoMessage()    {}
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{3}
}

func (m *GetDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentRequest.Unmarshal(m, b)
}
func (m *GetDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentRequest.Merge(m, src)
}
func (m *GetDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentRequest.Size(m)
}
func (m *GetDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentRequest proto.InternalMessageInfo

func (m *GetDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteDocumentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDocumentRequest) Reset()         { *m = DeleteDocumentRequest{} }
func (m *DeleteDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDocumentRequest) ProtoMessage()    {}
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{4}
}

func (m *DeleteDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDocumentRequest.Unmarshal(m, b)
}
func (m *DeleteDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDocumentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDocumentRequest.Merge(m, src)
}
func (m *DeleteDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDocumentRequest.Size(m)
}
func (m *DeleteDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDocumentRequest proto.InternalMessageInfo

func (m *DeleteDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListDocumentRequest struct {
	Filters              []*ListDocumentRequest_Filter `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ListDocumentRequest) Reset()         { *m = ListDocumentRequest{} }
func (m *ListDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*ListDocumentRequest) ProtoMessage()    {}
func (*ListDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{5}
}

func (m *ListDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentRequest.Unmarshal(m, b)
}
func (m *ListDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentRequest.Marshal(b, m, deterministic)
}
func (m *ListDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentRequest.Merge(m, src)
}
func (m *ListDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_ListDocumentRequest.Size(m)
}
func (m *ListDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentRequest proto.InternalMessageInfo

func (m *ListDocumentRequest) GetFilters() []*ListDocumentRequest_Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

type ListDocumentRequest_Filter struct {
	FieldPath            []string `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDocumentRequest_Filter) Reset()         { *m = ListDocumentRequest_Filter{} }
func (m *ListDocumentRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListDocumentRequest_Filter) ProtoMessage()    {}
func (*ListDocumentRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{5, 0}
}

func (m *ListDocumentRequest_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentRequest_Filter.Unmarshal(m, b)
}
func (m *ListDocumentRequest_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentRequest_Filter.Marshal(b, m, deterministic)
}
func (m *ListDocumentRequest_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentRequest_Filter.Merge(m, src)
}
func (m *ListDocumentRequest_Filter) XXX_Size() int {
	return xxx_messageInfo_ListDocumentRequest_Filter.Size(m)
}
func (m *ListDocumentRequest_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentRequest_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentRequest_Filter proto.InternalMessageInfo

func (m *ListDocumentRequest_Filter) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *ListDocumentRequest_Filter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListDocumentRequest_Filter) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

type DocumentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentResponse) Reset()         { *m = DocumentResponse{} }
func (m *DocumentResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentResponse) ProtoMessage()    {}
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{6}
}

func (m *DocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentResponse.Unmarshal(m, b)
}
func (m *DocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentResponse.Marshal(b, m, deterministic)
}
func (m *DocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentResponse.Merge(m, src)
}
func (m *DocumentResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentResponse.Size(m)
}
func (m *DocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentResponse proto.InternalMessageInfo

type GetDocumentResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	NotFound             bool     `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentResponse) Reset()         { *m = GetDocumentResponse{} }
func (m *GetDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*GetDocumentResponse) ProtoMessage()    {}
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{7}
}

func (m *GetDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentResponse.Unmarshal(m, b)
}
func (m *GetDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentResponse.Marshal(b, m, deterministic)
}
func (m *GetDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentResponse.Merge(m, src)
}
func (m *GetDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_GetDocumentResponse.Size(m)
}
func (m *GetDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentResponse proto.InternalMessageInfo

func (m *GetDocumentResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetDocumentResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type ListDocumentResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDocumentResponse) Reset()         { *m = ListDocumentResponse{} }
func (m *ListDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*ListDocumentResponse) ProtoMessage()    {}
func (*ListDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{8}
}

func (m *ListDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDocumentResponse.Unmarshal(m, b)
}
func (m *ListDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDocumentResponse.Marshal(b, m, deterministic)
}
func (m *ListDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDocumentResponse.Merge(m, src)
}
func (m *ListDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_ListDocumentResponse.Size(m)
}
func (m *ListDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDocumentResponse proto.InternalMessageInfo

func (m *ListDocumentResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListDocumentResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateDocumentResponse struct {
	AlreadyExists        bool     `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDocumentResponse) Reset()         { *m = CreateDocumentResponse{} }
func (m *CreateDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDocumentResponse) ProtoMessage()    {}
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{9}
}

func (m *CreateDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDocumentResponse.Unmarshal(m, b)
}
func (m *CreateDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDocumentResponse.Marshal(b, m, deterministic)
}
func (m *CreateDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDocumentResponse.Merge(m, src)
}
func (m *CreateDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDocumentResponse.Size(m)
}
func (m *CreateDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDocumentResponse proto.InternalMessageInfo

func (m *CreateDocumentResponse) GetAlreadyExists() bool {
	if m != nil {
		return m.AlreadyExists
	}
	return false
}

type UpdateDocumentResponse struct {
	NotFound             bool     `protobuf:"varint,1,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDocumentResponse) Reset()         { *m = UpdateDocumentResponse{} }
func (m *UpdateDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDocumentResponse) ProtoMessage()    {}
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_401c0b9c6cf607ff, []int{10}
}

func (m *UpdateDocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDocumentResponse.Unmarshal(m, b)
}
func (m *UpdateDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDocumentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDocumentResponse.Merge(m, src)
}
func (m *UpdateDocumentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDocumentResponse.Size(m)
}
func (m *UpdateDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDocumentResponse proto.InternalMessageInfo

func (m *UpdateDocumentResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func init() {
	proto.RegisterType((*CreateDocumentRequest)(nil), "rpc.CreateDocumentRequest")
	proto.RegisterType((*SetDocumentRequest)(nil), "rpc.SetDocumentRequest")
	proto.RegisterType((*UpdateDocumentRequest)(nil), "rpc.UpdateDocumentRequest")
	proto.RegisterType((*UpdateDocumentRequest_Update)(nil), "rpc.UpdateDocumentRequest.Update")
	proto.RegisterType((*GetDocumentRequest)(nil), "rpc.GetDocumentRequest")
	proto.RegisterType((*DeleteDocumentRequest)(nil), "rpc.DeleteDocumentRequest")
	proto.RegisterType((*ListDocumentRequest)(nil), "rpc.ListDocumentRequest")
	proto.RegisterType((*ListDocumentRequest_Filter)(nil), "rpc.ListDocumentRequest.Filter")
	proto.RegisterType((*DocumentResponse)(nil), "rpc.DocumentResponse")
	proto.RegisterType((*GetDocumentResponse)(nil), "rpc.GetDocumentResponse")
	proto.RegisterType((*ListDocumentResponse)(nil), "rpc.ListDocumentResponse")
	proto.RegisterType((*CreateDocumentResponse)(nil), "rpc.CreateDocumentResponse")
	proto.RegisterType((*UpdateDocumentResponse)(nil), "rpc.UpdateDocumentResponse")
}

func init() { proto.RegisterFile("rpc/datastore.proto", fileDescriptor_401c0b9c6cf607ff) }

var fileDescriptor_401c0b9c6cf607ff = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x97, 0x9b, 0x91, 0x35, 0x6f, 0x6c, 0x42, 0xee, 0x3a, 0x82, 0x07, 0xa2, 0x58, 0x20, 0x7a,
	0x2a, 0xa8, 0x68, 0xd2, 0x50, 0x85, 0x60, 0x62, 0x74, 0x17, 0x0e, 0xc8, 0x15, 0x07, 0x4e, 0x95,
	0x69, 0x5e, 0xb5, 0x48, 0x25, 0x36, 0xb6, 0x2b, 0xc1, 0x95, 0x6f, 0xc2, 0x99, 0x2f, 0x89, 0xea,
	0xb8, 0x1d, 0x5d, 0x52, 0x36, 0xf5, 0xd6, 0xfc, 0xde, 0xfb, 0xfd, 0x79, 0xcd, 0x7b, 0x81, 0x96,
	0xd1, 0x93, 0x17, 0x99, 0x74, 0xd2, 0x3a, 0x65, 0xb0, 0xa7, 0x8d, 0x72, 0x8a, 0x46, 0x46, 0x4f,
	0xf8, 0x00, 0xda, 0xef, 0x0d, 0x4a, 0x87, 0xe7, 0x6a, 0x32, 0xff, 0x86, 0x85, 0x13, 0xf8, 0x7d,
	0x8e, 0xd6, 0xd1, 0x03, 0x68, 0xe4, 0x59, 0x4a, 0x3a, 0xa4, 0x9b, 0x88, 0x46, 0x9e, 0x51, 0x0a,
	0x3b, 0x0b, 0x81, 0xb4, 0xd1, 0x21, 0xdd, 0xbb, 0xc2, 0xff, 0xe6, 0xa7, 0x40, 0x47, 0xe8, 0xb6,
	0x61, 0xfe, 0x26, 0xd0, 0xfe, 0xac, 0xb3, 0x5b, 0xf8, 0x0e, 0x60, 0x77, 0xee, 0x1b, 0x6d, 0xda,
	0xe8, 0x44, 0xdd, 0xbd, 0xfe, 0x93, 0x9e, 0xd1, 0x93, 0x5e, 0x2d, 0x39, 0xa0, 0x62, 0xc9, 0x60,
	0x03, 0x88, 0x4b, 0x88, 0x3e, 0x02, 0x98, 0xe6, 0x38, 0xcb, 0xc6, 0x5a, 0xba, 0xcb, 0x94, 0x74,
	0xa2, 0x6e, 0x22, 0x12, 0x8f, 0x7c, 0x92, 0xee, 0xb2, 0x36, 0xe3, 0x53, 0xa0, 0x17, 0x37, 0x4e,
	0xc7, 0x9f, 0x43, 0xfb, 0x1c, 0x67, 0x78, 0xe3, 0x20, 0xfc, 0x0f, 0x81, 0xd6, 0xc7, 0xdc, 0x56,
	0x04, 0x5f, 0xc3, 0xee, 0x34, 0x9f, 0x39, 0x34, 0xd6, 0xc7, 0xda, 0xeb, 0x3f, 0xf6, 0x03, 0xd6,
	0xb4, 0xf6, 0x86, 0xbe, 0x4f, 0x2c, 0xfb, 0xd9, 0x17, 0x88, 0x4b, 0x68, 0x8b, 0xf1, 0xe8, 0x43,
	0x48, 0x94, 0x46, 0x23, 0x5d, 0xae, 0x8a, 0x34, 0xf2, 0x31, 0xaf, 0x00, 0x4e, 0xe1, 0xde, 0x95,
	0xbb, 0xd5, 0xaa, 0xb0, 0xc8, 0x87, 0xd0, 0x5a, 0xfb, 0x43, 0x4a, 0x78, 0x25, 0x4e, 0xfe, 0x11,
	0x3f, 0x86, 0xa4, 0x50, 0x6e, 0x3c, 0x55, 0xf3, 0x22, 0xf3, 0xae, 0x4d, 0xd1, 0x2c, 0x94, 0x1b,
	0x2e, 0x9e, 0xf9, 0x3b, 0x38, 0x5c, 0x9f, 0xee, 0x3f, 0x42, 0x87, 0x70, 0x07, 0x8d, 0x51, 0xc6,
	0x8b, 0x24, 0xa2, 0x7c, 0xe0, 0x6f, 0xe1, 0xe8, 0xfa, 0xd6, 0x06, 0x8d, 0x67, 0x70, 0x20, 0x67,
	0x06, 0x65, 0xf6, 0x73, 0x8c, 0x3f, 0x72, 0xeb, 0xac, 0x57, 0x6b, 0x8a, 0xfd, 0x80, 0x7e, 0xf0,
	0x20, 0x3f, 0x81, 0xa3, 0xeb, 0x1b, 0x14, 0x04, 0xd6, 0x92, 0x93, 0xf5, 0xe4, 0xfd, 0x5f, 0x11,
	0xec, 0x2f, 0x19, 0xa3, 0xc5, 0x29, 0xd1, 0x33, 0x88, 0xcb, 0x24, 0x94, 0xf9, 0xd7, 0x56, 0x7b,
	0x4c, 0xec, 0xb8, 0xb6, 0x16, 0x1c, 0x4f, 0x20, 0x1a, 0xa1, 0xa3, 0xf7, 0x7d, 0x4f, 0xf5, 0x9e,
	0x58, 0xdb, 0x17, 0x2a, 0xb4, 0xb3, 0xd5, 0x6e, 0xb3, 0xcd, 0x17, 0x11, 0x9c, 0x37, 0xcc, 0x7a,
	0x0a, 0xd1, 0xc5, 0xca, 0xb9, 0xba, 0xeb, 0x2c, 0xad, 0x16, 0x02, 0x73, 0x00, 0x71, 0xb9, 0xf5,
	0xc1, 0xbc, 0xf6, 0x04, 0x36, 0x25, 0x7f, 0x03, 0x3b, 0x8b, 0xf7, 0x4f, 0xd3, 0x4d, 0x8b, 0xce,
	0x1e, 0xd4, 0x54, 0x4a, 0xf2, 0x4b, 0xf2, 0x35, 0xf6, 0x9f, 0xaf, 0x57, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xd2, 0x6b, 0x24, 0x12, 0xd5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentStoreClient interface {
	Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (DocumentStore_ListClient, error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, "/rpc.DocumentStore/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/rpc.DocumentStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, "/rpc.DocumentStore/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/rpc.DocumentStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/rpc.DocumentStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (DocumentStore_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DocumentStore_serviceDesc.Streams[0], "/rpc.DocumentStore/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentStoreListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DocumentStore_ListClient interface {
	Recv() (*ListDocumentResponse, error)
	grpc.ClientStream
}

type documentStoreListClient struct {
	grpc.ClientStream
}

func (x *documentStoreListClient) Recv() (*ListDocumentResponse, error) {
	m := new(ListDocumentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentStoreServer is the server API for DocumentStore service.
type DocumentStoreServer interface {
	Create(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	Set(context.Context, *SetDocumentRequest) (*DocumentResponse, error)
	Update(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error)
	List(*ListDocumentRequest, DocumentStore_ListServer) error
}

// UnimplementedDocumentStoreServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentStoreServer struct {
}

func (*UnimplementedDocumentStoreServer) Create(ctx context.Context, req *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedDocumentStoreServer) Set(ctx context.Context, req *SetDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedDocumentStoreServer) Update(ctx context.Context, req *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedDocumentStoreServer) Get(ctx context.Context, req *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedDocumentStoreServer) Delete(ctx context.Context, req *DeleteDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedDocumentStoreServer) List(req *ListDocumentRequest, srv DocumentStore_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterDocumentStoreServer(s *grpc.Server, srv DocumentStoreServer) {
	s.RegisterService(&_DocumentStore_serviceDesc, srv)
}

func _DocumentStore_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DocumentStore/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Create(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DocumentStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Set(ctx, req.(*SetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DocumentStore/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Update(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DocumentStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Get(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DocumentStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Delete(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).List(m, &documentStoreListServer{stream})
}

type DocumentStore_ListServer interface {
	Send(*ListDocumentResponse) error
	grpc.ServerStream
}

type documentStoreListServer struct {
	grpc.ServerStream
}

func (x *documentStoreListServer) Send(m *ListDocumentResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DocumentStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DocumentStore_Create_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _DocumentStore_Set_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DocumentStore_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DocumentStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocumentStore_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DocumentStore_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/datastore.proto",
}
