// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/gps.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinates struct {
	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude  float32 `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// FIXME add tests to catch missing this parameter
	Time                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	DeviceID             string               `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_97f9da05977eb288, []int{0}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinates) GetAltitude() float32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Coordinates) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Coordinates) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func init() {
	proto.RegisterType((*Coordinates)(nil), "rpc.Coordinates")
}

func init() { proto.RegisterFile("rpc/gps.proto", fileDescriptor_97f9da05977eb288) }

var fileDescriptor_97f9da05977eb288 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2a, 0x48, 0xd6,
	0x4f, 0x2f, 0x28, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x96, 0x92,
	0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6,
	0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x54, 0x29, 0xad, 0x67, 0xe4, 0xe2, 0x76, 0xce, 0xcf,
	0x2f, 0x4a, 0xc9, 0xcc, 0x4b, 0x2c, 0x49, 0x2d, 0x16, 0x92, 0xe2, 0xe2, 0xc8, 0x49, 0x2c, 0xc9,
	0x2c, 0x29, 0x4d, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0a, 0x82, 0xf3, 0x85, 0x64, 0xb8,
	0x38, 0x73, 0xf2, 0xf3, 0xd2, 0x21, 0x92, 0x4c, 0x60, 0x49, 0x84, 0x00, 0x48, 0x67, 0x62, 0x0e,
	0x54, 0x27, 0x33, 0x44, 0x27, 0x8c, 0x2f, 0xa4, 0xc7, 0xc5, 0x02, 0xb2, 0x58, 0x82, 0x45, 0x81,
	0x51, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0xe2, 0x2a, 0x3d, 0x98, 0xab, 0xf4, 0x42, 0x60, 0xae, 0x0a,
	0x02, 0xab, 0x03, 0x99, 0x95, 0x92, 0x5a, 0x96, 0x99, 0x9c, 0xea, 0xe9, 0x22, 0xc1, 0xaa, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x27, 0xb1, 0x81, 0x75, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x7d, 0x79, 0xb3, 0xef, 0x00, 0x00, 0x00,
}
