// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/gps.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Coordinates struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude             float32  `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	UnixTime             int64    `protobuf:"varint,4,opt,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	DeviceID             string   `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_97f9da05977eb288, []int{0}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinates) GetAltitude() float32 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *Coordinates) GetUnixTime() int64 {
	if m != nil {
		return m.UnixTime
	}
	return 0
}

func (m *Coordinates) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func init() {
	proto.RegisterType((*Coordinates)(nil), "rpc.Coordinates")
}

func init() { proto.RegisterFile("rpc/gps.proto", fileDescriptor_97f9da05977eb288) }

var fileDescriptor_97f9da05977eb288 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2a, 0x48, 0xd6,
	0x4f, 0x2f, 0x28, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x9a,
	0xc3, 0xc8, 0xc5, 0xed, 0x9c, 0x9f, 0x5f, 0x94, 0x92, 0x99, 0x97, 0x58, 0x92, 0x5a, 0x2c, 0x24,
	0xc5, 0xc5, 0x91, 0x93, 0x58, 0x92, 0x59, 0x52, 0x9a, 0x92, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x14, 0x04, 0xe7, 0x0b, 0xc9, 0x70, 0x71, 0xe6, 0xe4, 0xe7, 0xa5, 0x43, 0x24, 0x99, 0xc0, 0x92,
	0x08, 0x01, 0x90, 0xce, 0xc4, 0x1c, 0xa8, 0x4e, 0x66, 0x88, 0x4e, 0x18, 0x5f, 0x48, 0x9a, 0x8b,
	0xb3, 0x34, 0x2f, 0xb3, 0x22, 0xbe, 0x24, 0x33, 0x37, 0x55, 0x82, 0x45, 0x81, 0x51, 0x83, 0x39,
	0x88, 0x03, 0x24, 0x10, 0x92, 0x99, 0x0b, 0xd6, 0x98, 0x92, 0x5a, 0x96, 0x99, 0x9c, 0xea, 0xe9,
	0x22, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x27, 0xb1, 0x81, 0x9d, 0x6a, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x8e, 0x75, 0xea, 0x1d, 0xbb, 0x00, 0x00, 0x00,
}
