// Unstable Build LLC ("COMPANY") CONFIDENTIAL
//
// Unpublished Copyright (c) 2018-2024 Unstable Build, All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of COMPANY.
// The intellectual and technical concepts contained herein are proprietary to
// COMPANY and may be covered by U.S. and Foreign Patents, patents in process,
// and are protected by trade secret or copyright law. Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written permission
// is obtained from COMPANY. Access to the source code contained herein is hereby
// forbidden to anyone except current COMPANY employees, managers or contractors who
// have executed Confidentiality and Non-disclosure agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or
// disclosure of this source code, which includes information that is confidential and/or
// proprietary, and is a trade secret, of COMPANY. ANY REPRODUCTION, MODIFICATION,
// DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE
// WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN
// VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF
// THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
// REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL
// ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

package openai

import (
	"fmt"

	"github.com/sashabaranov/go-openai"
	"github.com/unstablebuild/blue/ai/llm"
)

// Metadata is set in llm.ChatCompletionResponse's Metadata.
type Metadata struct {
	// For Role=assistant prompts this may be set to the tool calls generated by the model, such as function calls.
	ToolCalls []ToolCall
}

// ToolType is the type of tool that a model can invoke.
type ToolType string

const (
	// ToolTypeFunction defines a function tool.
	ToolTypeFunction ToolType = "function"
)

// ToolCall is the result of a model call to a tool.
type ToolCall struct {
	// Index is not nil only in chat completion chunk object
	Index    *int
	ID       string
	Type     ToolType
	Function FunctionCall
}

// Tool is a resource that the model may use (like functions, files, etc.).
type Tool struct {
	Type     ToolType
	Function FunctionDefinition
}

// FunctionDefinition defines  functions that can be "called" by the model.
type FunctionDefinition struct {
	Name        string
	Description string
	// Parameters is an object describing the function.
	// You can pass a raw byte array describing the schema,
	// or you can pass in a struct which serializes to the proper JSONSchema.
	// The JSONSchemaDefinition struct is provided for convenience, but you should
	// consider another specialized library for more complex schemas.
	Parameters any
}

// FunctionCall is a function call requested by the user, as specified in the
// ChatCompletionRequest.
type FunctionCall struct {
	Name string
	// call function with arguments in JSON format
	Arguments string
}

func openAIMultiContentFromModel(
	msg []llm.ChatMessagePart,
) (ret []openai.ChatMessagePart) {
	if len(msg) == 0 {
		return
	}
	ret = make([]openai.ChatMessagePart, len(msg))
	for i, part := range msg {
		openaiPart := openai.ChatMessagePart{
			Text: part.Text,
		}
		switch part.Type {
		case llm.ChatMessagePartTypeImageURL:
			openaiPart.Type = openai.ChatMessagePartTypeImageURL
		default: // case ChatMessagePartTypeText:
			openaiPart.Type = openai.ChatMessagePartTypeText
		}
		if part.ImageURL != "" {
			openaiPart.ImageURL = &openai.ChatMessageImageURL{
				URL:    part.ImageURL,
				Detail: openai.ImageURLDetailAuto,
			}
		}
		ret[i] = openaiPart
	}
	return
}

func openAIMessageFromModel(
	msg llm.ChatCompletionMessage,
) (ret openai.ChatCompletionMessage, err error) {
	var toolCalls []openai.ToolCall
	if msg.Metadata != nil {
		toolCalls = openAIToolCallsFromModel(msg.Metadata.(Metadata).ToolCalls)
	}
	var role string
	switch msg.Role {
	case llm.RoleAssistant:
		role = openai.ChatMessageRoleAssistant
	case llm.RoleUser:
		role = openai.ChatMessageRoleUser
	case llm.RoleSystem:
		role = openai.ChatMessageRoleSystem
	case llm.RoleTool:
		role = openai.ChatMessageRoleTool
	case "function":
		role = openai.ChatMessageRoleFunction
	default:
		err = fmt.Errorf("role %q is unrecognized by openai's API", msg.Role)
		return
	}
	ret = openai.ChatCompletionMessage{
		Role:         role,
		Content:      msg.Content,
		MultiContent: openAIMultiContentFromModel(msg.OtherContent),
		ToolCalls:    toolCalls,
		Name:         msg.Name,
	}
	return
}

func openAIToolCallsFromModel(tools []ToolCall) (ret []openai.ToolCall) {
	if len(tools) == 0 {
		return
	}
	ret = make([]openai.ToolCall, len(tools))
	for i, call := range tools {
		ret[i] = openai.ToolCall{
			Index: call.Index,
			ID:    call.ID,
			Type:  openai.ToolType(call.Type),
			Function: openai.FunctionCall{
				Name:      call.Function.Name,
				Arguments: call.Function.Arguments,
			},
		}
	}
	return
}

func modelToolCallsFromOpenAI(tools []openai.ToolCall) (ret []ToolCall) {
	if len(tools) == 0 {
		return
	}
	ret = make([]ToolCall, len(tools))
	for i, tool := range tools {
		ret[i] = ToolCall{
			Index: tool.Index,
			ID:    tool.ID,
			Type:  ToolType(tool.Type),
			Function: FunctionCall{
				Name:      tool.Function.Name,
				Arguments: tool.Function.Arguments,
			},
		}
	}
	return
}

func openAIResponseFormatFromModel(format *ChatCompletionResponseFormat) (
	ret *openai.ChatCompletionResponseFormat,
) {
	if format == nil {
		return
	}

	ret = new(openai.ChatCompletionResponseFormat)
	switch format.Type {
	case ChatCompletionResponseFormatTypeJSONObject:
		ret.Type = openai.ChatCompletionResponseFormatTypeJSONObject
	case ChatCompletionResponseFormatTypeJSONSchema:
		ret.Type = openai.ChatCompletionResponseFormatTypeJSONSchema
	case ChatCompletionResponseFormatTypeText:
		ret.Type = openai.ChatCompletionResponseFormatTypeText
	}

	if format.JSONSchema == nil {
		return
	}

	ret.JSONSchema = new(openai.ChatCompletionResponseFormatJSONSchema)
	ret.JSONSchema.Name = format.JSONSchema.Name
	ret.JSONSchema.Description = format.JSONSchema.Description
	ret.JSONSchema.Schema = format.JSONSchema.Schema
	ret.JSONSchema.Strict = format.JSONSchema.Strict

	return
}
