// Unstable Build LLC ("COMPANY") CONFIDENTIAL
//
// Unpublished Copyright (c) 2018-2024 Unstable Build, All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of COMPANY.
// The intellectual and technical concepts contained herein are proprietary to
// COMPANY and may be covered by U.S. and Foreign Patents, patents in process,
// and are protected by trade secret or copyright law. Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written permission
// is obtained from COMPANY. Access to the source code contained herein is hereby
// forbidden to anyone except current COMPANY employees, managers or contractors who
// have executed Confidentiality and Non-disclosure agreements explicitly covering such access.
//
// The copyright notice above does not evidence any actual or intended publication or
// disclosure of this source code, which includes information that is confidential and/or
// proprietary, and is a trade secret, of COMPANY. ANY REPRODUCTION, MODIFICATION,
// DISTRIBUTION, PUBLIC  PERFORMANCE, OR PUBLIC DISPLAY OF OR THROUGH USE OF THIS SOURCE CODE
// WITHOUT  THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED, AND IN
// VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES. THE RECEIPT OR POSSESSION OF
// THIS SOURCE CODE AND/OR RELATED INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS TO
// REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL
// ANYTHING THAT IT MAY DESCRIBE, IN WHOLE OR IN PART.

package openai

import (
	"context"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/pkoukk/tiktoken-go"
	tiktokenLoader "github.com/pkoukk/tiktoken-go-loader"
	"github.com/sashabaranov/go-openai"
	log "github.com/sirupsen/logrus"
	"github.com/unstablebuild/blue/ai/llm"
	"github.com/unstablebuild/blue/iterator"
	"github.com/unstablebuild/blue/logging"
	"github.com/unstablebuild/blue/retry"
)

// Config represents the default parameters used for chat completions
// along with the configuration passed to the openai client.
type Config struct {
	// ID of the model to use. If this is not set NewClient panics.
	Model string
	// Number between -2.0 and 2.0. Positive values penalize new tokens based
	// on their existing frequency in the text so far, decreasing the model's likelihood
	// to repeat the same line verbatim.
	FrequencyPenalty float64
	// Modify the likelihood of specified tokens appearing in the completion.
	//Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer)
	// to an associated bias value from -100 to 100. Mathematically, the bias is added to
	// the logits generated by the model prior to sampling. The exact effect will vary per model,
	// but values between -1 and 1 should decrease or increase likelihood of selection;
	// values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
	LogitBias map[string]int
	// The maximum number of tokens to generate in the chat completion.
	// The total length of input tokens and generated tokens is limited by the model's
	// context length.
	MaxTokens int

	// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they
	// appear in the text so far, increasing the model's likelihood to talk about new topics.
	PresencePenalty float64
	// If specified, our system will make a best effort to sample deterministically, such that repeated
	// requests with the same seed and parameters should return the same result.
	// Determinism is not guaranteed, and you should refer to the system_fingerprint response
	// parameter to monitor changes in the llm.
	// In beta, currently.
	// Seed int

	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
	// make the output more random, while lower values like 0.2 will make it more
	// focused and deterministic.
	// Openai generally recommends altering this or top_p but not both.
	Temperature float64
	// An alternative to sampling with temperature, called nucleus sampling,
	// where the model considers the results of the tokens with top_p probability mass.
	// So 0.1 means only the tokens comprising the top 10% probability mass are considered.
	// Openai generally recommends altering this or temperature but not both.
	TopP float64

	// A list of tools the model may call. Currently, only functions are supported
	// as a tool. Use this to provide a list of functions the model may generate JSON inputs for.
	Tools []Tool
	// BaseURL for of the http service.
	BaseURL string
}

// NewClient returns a backedn.Service backed by openai's text completion API.
//
// The iterator returned by CreateChatCompletion sets ChatCompletionResponse's
// Metadata to a type openai.Metadata struct.
func NewClient(
	token string, config Config,
	availableModels map[string]int,
) llm.Service {
	if config.Model == "" {
		panic("Config.Model cannot be empty")
	}

	if _, ok := availableModels[config.Model]; !ok {
		panic(fmt.Errorf("model not in available models: %s vs %+v", config.Model, availableModels))
	}

	var tools []openai.Tool
	for _, tool := range config.Tools {
		tools = append(tools, openai.Tool{
			Type: openai.ToolType(tool.Type),
			Function: &openai.FunctionDefinition{
				Name:        tool.Function.Name,
				Description: tool.Function.Description,
				Parameters:  tool.Function.Parameters,
			},
		})
	}

	tkm, err := tiktoken.EncodingForModel(config.Model)
	if err != nil {
		(client{}).log(log.WarnLevel, "token counting might be off: encoding for model %s: %v",
			config.Model, err)
		tkm, err = tiktoken.EncodingForModel(GPT4)
		if err != nil {
			panic(fmt.Errorf("fallback encoding for model "+
				"from %s to %s failed: %v", config.Model, GPT4, err))
		}
	}

	var tokensPerMessage, tokensPerName int
	switch config.Model {
	case "gpt-3.5-turbo-0301":
		tokensPerMessage = 4 // every message follows <|start|>{role/name}\n{content}<|end|>\n
		tokensPerName = -1   // if there's a name, the role is omitted
	default:
		tokensPerMessage = 3
		tokensPerName = 1
	}

	openaiConfig := openai.DefaultConfig(token)
	if config.BaseURL != "" {
		openaiConfig.BaseURL = config.BaseURL
	}
	c := openai.NewClientWithConfig(openaiConfig)

	return client{
		tools:              tools,
		config:             config,
		client:             c,
		counter:            tkm,
		tokensPerMessage:   tokensPerMessage,
		tokensPerName:      tokensPerName,
		modelContextWindow: availableModels,
	}
}

func init() {
	// NOTE: do not load bpe loader every time extension fires
	// as it needs an environment variable to cache it and manage it.
	// We should probably download dynamically and manage the cache
	// manually via host storage service, so the extension binary size
	// doesn't suffer from embeds, but for now it's fine since
	// this should rarely change.
	tiktoken.SetBpeLoader(tiktokenLoader.NewOfflineLoader())
}

var (
	retryStrategy = retry.CombinedStrategy(
		retry.LimitStrategy(5),
		retry.ExponentialStrategy(100*time.Millisecond, 2000*time.Millisecond),
	)
)

type client struct {
	tools              []openai.Tool
	config             Config
	client             *openai.Client
	counter            *tiktoken.Tiktoken
	tokensPerMessage   int
	tokensPerName      int
	modelContextWindow map[string]int
}

func (a client) log(level log.Level, msg string, args ...any) {
	if !log.IsLevelEnabled(level) {
		return
	}
	log.WithFields(log.Fields{
		logging.KeyClass: "openai.Client",
		"model":          a.config.Model,
	}).Logf(level, msg, args...)
}

func (a client) CreateChatCompletion(
	ctx context.Context, request llm.ChatCompletionRequest,
) (iterator.Iterator[llm.ChatCompletionResponse], error) {
	messages := make([]openai.ChatCompletionMessage, len(request.Messages))
	for i, msg := range request.Messages {
		var err error
		messages[i], err = openAIMessageFromModel(msg)
		if err != nil {
			return nil, err
		}
	}

	count := a.countTokens(request.Messages)
	max := a.modelContextWindow[a.config.Model]
	if count > max {
		return nil, &llm.ErrContextWindowExceeded{Count: count, Max: max}
	}

	req := openai.ChatCompletionRequest{
		Messages:         messages,
		Model:            a.config.Model,
		FrequencyPenalty: float32(a.config.FrequencyPenalty),
		LogitBias:        a.config.LogitBias,
		MaxTokens:        a.config.MaxTokens,
		PresencePenalty:  float32(a.config.PresencePenalty),
		Temperature:      float32(a.config.Temperature),
		TopP:             float32(a.config.TopP),
		Tools:            a.tools,
		// NOTE: openai's choices/N API is not very useful at the moment
		// so we simply do not allow user to employ it
		// which greatly simplifies the llm.Service interface.
		// N:                1,
	}

	// see https://platform.openai.com/docs/guides/error-codes/api-errors
	var stream *openai.ChatCompletionStream
	var n int
	ctx, cancel := context.WithCancel(ctx)
	err := retry.Retry(ctx, retryStrategy, func(ctx context.Context) (bool, error) {
		n++
		var err error
		stream, err = a.client.CreateChatCompletionStream(ctx, req)
		if err == nil {
			return false, nil // done
		}
		apiErr := &openai.APIError{}
		if !errors.As(err, &apiErr) {
			return false, err // do not retry unknown error
		}
		fields := log.Fields{
			"call":           "CreateChatCompletion",
			"attempt":        n,
			"code":           apiErr.HTTPStatusCode,
			logging.KeyError: err.Error(),
			logging.KeyClass: "openai.Client",
		}
		switch apiErr.HTTPStatusCode {
		case 429:
			// for now treat rate limit headers as just logging data
			// If this impl proves to be insufficient for prod,
			// we should use the max of reset requests and reset tokens time
			// to dynamically provide a retry strategy.
			if stream != nil {
				headers := stream.GetRateLimitHeaders()
				fields["headerLimitRequests"] = headers.LimitRequests
				fields["headerLimitTokens"] = headers.LimitTokens
				fields["headerRemainingRequests"] = headers.RemainingRequests
				fields["headerRemainingTokens"] = headers.RemainingTokens
				fields["headerResetRequests"] = headers.ResetRequests
				fields["headerResetTokens"] = headers.ResetTokens
			}
			fallthrough
		case 500, 503:
			log.WithFields(fields).Warn(apiErr.Message)
			return true, err // retry allowed codes
		default:
			return false, err // do not retry the rest
		}
	})
	if err != nil {
		cancel()
		return nil, err
	}
	it := iterator.FromValueStream[openai.ChatCompletionStreamResponse](ctx, cancel, stream)
	return &completionStreamIterator{client: a, it: it}, nil
}

func (a client) ExceedsContextWindow(messages []llm.ChatCompletionMessage) (bool, error) {
	return a.countTokens(messages) > a.modelContextWindow[a.config.Model], nil
}

// OpenAI Cookbook: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
func (a client) countTokens(messages []llm.ChatCompletionMessage) (ret int) {
	for _, message := range messages {
		ret += a.tokensPerMessage
		ret += len(a.counter.Encode(message.Content, nil, nil))
		ret += len(a.counter.Encode(string(message.Role), nil, nil))
		ret += len(a.counter.Encode(message.Name, nil, nil))
		if message.Name != "" {
			ret += a.tokensPerName
		}
	}
	ret += 3
	return
}

// wraps an openai.ChatCompletionStream to satisfy iterator.Iterator
type completionStreamIterator struct {
	client
	role llm.Role
	it   iterator.Iterator[openai.ChatCompletionStreamResponse]
	err  error
	meta any
}

func (s *completionStreamIterator) Next(ctx context.Context) (
	ret llm.ChatCompletionResponse, ok bool,
) {
	resp, ok := s.it.Next(ctx)
	if !ok {
		err := s.it.Err()
		if err != nil {
			if !errors.Is(err, io.EOF) {
				s.err = err
			}
		}
		return
	}
	// NOTE: see above N parameter config
	choice := resp.Choices[0]

	s.client.log(log.TraceLevel, "received llm response: %+v", choice)

	if s.role == "" {
		switch choice.Delta.Role {
		case openai.ChatMessageRoleSystem:
			s.role = llm.RoleSystem
		case openai.ChatMessageRoleUser:
			s.role = llm.RoleUser
		case openai.ChatMessageRoleAssistant:
			s.role = llm.RoleAssistant
		case openai.ChatMessageRoleFunction:
			s.role = "function"
		case openai.ChatMessageRoleTool:
			s.role = llm.RoleTool
		default:
			s.err = fmt.Errorf("role %q is unrecognized by llm API", choice.Delta.Role)
		}
	}
	ok = true

	// only set Metadata if ToolCalls is not 0
	// this way clients agnostic to openai's llm
	// can simply check if Metadata is nil to perform
	// something different, like calling a metadata handler
	// (that knows about openai).
	if len(choice.Delta.ToolCalls) != 0 {
		// ensure that the last message's Metadata contains
		// all the streamed arguments.
		s.appendToolCallsArguments(choice.Delta.ToolCalls)
	}

	ret = llm.ChatCompletionResponse{
		ID:      resp.ID,
		Created: time.Unix(resp.Created, 0),
		Message: llm.ChatCompletionMessage{
			Role:     s.role,
			Content:  choice.Delta.Content,
			Metadata: s.meta,
			// Name: assistant's name is never defined;
			// at least the unofficial openai client doesn't defined
		},
		FinishReason: llm.FinishReason(choice.FinishReason),
	}
	s.client.log(log.TraceLevel, "streaming response %+v", ret)
	return
}

// Err returns the first error or an aggreation of the errors
// encountered by the Iterator.
func (s *completionStreamIterator) Err() error {
	return s.err
}
func (s *completionStreamIterator) Close() error {
	return s.it.Close()
}

func (s *completionStreamIterator) appendToolCallsArguments(newToolCallsArgs []openai.ToolCall) {
	if s.meta == nil {
		s.meta = Metadata{
			ToolCalls: modelToolCallsFromOpenAI(newToolCallsArgs),
		}
		return
	}
	toolCalls := s.meta.(Metadata).ToolCalls
	if len(newToolCallsArgs) != len(toolCalls) {
		s.client.log(log.ErrorLevel, "inconsistent number of tool calls "+
			"within a stream of chat completion messages")
		return
	}
	for i, tool := range newToolCallsArgs {
		toolCalls[i].Function.Arguments = toolCalls[i].Function.Arguments + tool.Function.Arguments
	}
	s.meta = Metadata{ToolCalls: toolCalls}
}
