// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: docpb/datastore.proto

package docpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentStoreClient is the client API for DocumentStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentStoreClient interface {
	Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error)
	Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error)
	Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (DocumentStore_ListClient, error)
}

type documentStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentStoreClient(cc grpc.ClientConnInterface) DocumentStoreClient {
	return &documentStoreClient{cc}
}

func (c *documentStoreClient) Create(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*CreateDocumentResponse, error) {
	out := new(CreateDocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentStore/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Set(ctx context.Context, in *SetDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentStore/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Update(ctx context.Context, in *UpdateDocumentRequest, opts ...grpc.CallOption) (*UpdateDocumentResponse, error) {
	out := new(UpdateDocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentStore/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Get(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentStore/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) Delete(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentStore/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentStoreClient) List(ctx context.Context, in *ListDocumentRequest, opts ...grpc.CallOption) (DocumentStore_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &DocumentStore_ServiceDesc.Streams[0], "/proto.DocumentStore/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &documentStoreListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DocumentStore_ListClient interface {
	Recv() (*ListDocumentResponse, error)
	grpc.ClientStream
}

type documentStoreListClient struct {
	grpc.ClientStream
}

func (x *documentStoreListClient) Recv() (*ListDocumentResponse, error) {
	m := new(ListDocumentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DocumentStoreServer is the server API for DocumentStore service.
// All implementations must embed UnimplementedDocumentStoreServer
// for forward compatibility
type DocumentStoreServer interface {
	Create(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error)
	Set(context.Context, *SetDocumentRequest) (*DocumentResponse, error)
	Update(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error)
	Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error)
	List(*ListDocumentRequest, DocumentStore_ListServer) error
	mustEmbedUnimplementedDocumentStoreServer()
}

// UnimplementedDocumentStoreServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentStoreServer struct {
}

func (UnimplementedDocumentStoreServer) Create(context.Context, *CreateDocumentRequest) (*CreateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDocumentStoreServer) Set(context.Context, *SetDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedDocumentStoreServer) Update(context.Context, *UpdateDocumentRequest) (*UpdateDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDocumentStoreServer) Get(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDocumentStoreServer) Delete(context.Context, *DeleteDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocumentStoreServer) List(*ListDocumentRequest, DocumentStore_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDocumentStoreServer) mustEmbedUnimplementedDocumentStoreServer() {}

// UnsafeDocumentStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentStoreServer will
// result in compilation errors.
type UnsafeDocumentStoreServer interface {
	mustEmbedUnimplementedDocumentStoreServer()
}

func RegisterDocumentStoreServer(s grpc.ServiceRegistrar, srv DocumentStoreServer) {
	s.RegisterService(&DocumentStore_ServiceDesc, srv)
}

func _DocumentStore_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentStore/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Create(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentStore/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Set(ctx, req.(*SetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentStore/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Update(ctx, req.(*UpdateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Get(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentStoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentStore/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentStoreServer).Delete(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentStore_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDocumentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DocumentStoreServer).List(m, &documentStoreListServer{stream})
}

type DocumentStore_ListServer interface {
	Send(*ListDocumentResponse) error
	grpc.ServerStream
}

type documentStoreListServer struct {
	grpc.ServerStream
}

func (x *documentStoreListServer) Send(m *ListDocumentResponse) error {
	return x.ServerStream.SendMsg(m)
}

// DocumentStore_ServiceDesc is the grpc.ServiceDesc for DocumentStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DocumentStore",
	HandlerType: (*DocumentStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DocumentStore_Create_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _DocumentStore_Set_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DocumentStore_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DocumentStore_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocumentStore_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DocumentStore_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "docpb/datastore.proto",
}
