// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: pubsubpb/pubsub.proto

package pubsubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PublishRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{1}
}

type ReceiveMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Ack           *ReceiveMessage_Ack     `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Data          *ReceiveMessage_Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Req           *ReceiveMessage_Request `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage) Reset() {
	*x = ReceiveMessage{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage) ProtoMessage() {}

func (x *ReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage.ProtoReflect.Descriptor instead.
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{2}
}

func (x *ReceiveMessage) GetAck() *ReceiveMessage_Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *ReceiveMessage) GetData() *ReceiveMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReceiveMessage) GetReq() *ReceiveMessage_Request {
	if x != nil {
		return x.Req
	}
	return nil
}

type ReceiveMessage_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage_Data) Reset() {
	*x = ReceiveMessage_Data{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage_Data) ProtoMessage() {}

func (x *ReceiveMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage_Data.ProtoReflect.Descriptor instead.
func (*ReceiveMessage_Data) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReceiveMessage_Data) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ReceiveMessage_Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReceiveMessage_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage_Request) Reset() {
	*x = ReceiveMessage_Request{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage_Request) ProtoMessage() {}

func (x *ReceiveMessage_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage_Request.ProtoReflect.Descriptor instead.
func (*ReceiveMessage_Request) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ReceiveMessage_Request) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ReceiveMessage_Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage_Ack) Reset() {
	*x = ReceiveMessage_Ack{}
	mi := &file_pubsubpb_pubsub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage_Ack) ProtoMessage() {}

func (x *ReceiveMessage_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pubsubpb_pubsub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage_Ack.ProtoReflect.Descriptor instead.
func (*ReceiveMessage_Ack) Descriptor() ([]byte, []int) {
	return file_pubsubpb_pubsub_proto_rawDescGZIP(), []int{2, 2}
}

var File_pubsubpb_pubsub_proto protoreflect.FileDescriptor

const file_pubsubpb_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x15pubsubpb/pubsub.proto\x12\x05proto\"R\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\"\x11\n" +
	"\x0fPublishResponse\"\xfa\x01\n" +
	"\x0eReceiveMessage\x12+\n" +
	"\x03ack\x18\x01 \x01(\v2\x19.proto.ReceiveMessage.AckR\x03ack\x12.\n" +
	"\x04data\x18\x02 \x01(\v2\x1a.proto.ReceiveMessage.DataR\x04data\x12/\n" +
	"\x03req\x18\x03 \x01(\v2\x1d.proto.ReceiveMessage.RequestR\x03req\x1a2\n" +
	"\x04Data\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x1a\x05\n" +
	"\x03Ack2\x7f\n" +
	"\x06PubSub\x128\n" +
	"\aPublish\x12\x15.proto.PublishRequest\x1a\x16.proto.PublishResponse\x12;\n" +
	"\aReceive\x12\x15.proto.ReceiveMessage\x1a\x15.proto.ReceiveMessage(\x010\x01B\vZ\t/pubsubpbb\x06proto3"

var (
	file_pubsubpb_pubsub_proto_rawDescOnce sync.Once
	file_pubsubpb_pubsub_proto_rawDescData []byte
)

func file_pubsubpb_pubsub_proto_rawDescGZIP() []byte {
	file_pubsubpb_pubsub_proto_rawDescOnce.Do(func() {
		file_pubsubpb_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pubsubpb_pubsub_proto_rawDesc), len(file_pubsubpb_pubsub_proto_rawDesc)))
	})
	return file_pubsubpb_pubsub_proto_rawDescData
}

var file_pubsubpb_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pubsubpb_pubsub_proto_goTypes = []any{
	(*PublishRequest)(nil),         // 0: proto.PublishRequest
	(*PublishResponse)(nil),        // 1: proto.PublishResponse
	(*ReceiveMessage)(nil),         // 2: proto.ReceiveMessage
	(*ReceiveMessage_Data)(nil),    // 3: proto.ReceiveMessage.Data
	(*ReceiveMessage_Request)(nil), // 4: proto.ReceiveMessage.Request
	(*ReceiveMessage_Ack)(nil),     // 5: proto.ReceiveMessage.Ack
}
var file_pubsubpb_pubsub_proto_depIdxs = []int32{
	5, // 0: proto.ReceiveMessage.ack:type_name -> proto.ReceiveMessage.Ack
	3, // 1: proto.ReceiveMessage.data:type_name -> proto.ReceiveMessage.Data
	4, // 2: proto.ReceiveMessage.req:type_name -> proto.ReceiveMessage.Request
	0, // 3: proto.PubSub.Publish:input_type -> proto.PublishRequest
	2, // 4: proto.PubSub.Receive:input_type -> proto.ReceiveMessage
	1, // 5: proto.PubSub.Publish:output_type -> proto.PublishResponse
	2, // 6: proto.PubSub.Receive:output_type -> proto.ReceiveMessage
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pubsubpb_pubsub_proto_init() }
func file_pubsubpb_pubsub_proto_init() {
	if File_pubsubpb_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pubsubpb_pubsub_proto_rawDesc), len(file_pubsubpb_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pubsubpb_pubsub_proto_goTypes,
		DependencyIndexes: file_pubsubpb_pubsub_proto_depIdxs,
		MessageInfos:      file_pubsubpb_pubsub_proto_msgTypes,
	}.Build()
	File_pubsubpb_pubsub_proto = out.File
	file_pubsubpb_pubsub_proto_goTypes = nil
	file_pubsubpb_pubsub_proto_depIdxs = nil
}
