// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go

// Package release is a generated GoMock package.
package release

import (
	context "context"
	reflect "reflect"

	debug "github.com/ernestrc/blue/debug"
	gomock "github.com/golang/mock/gomock"
)

// MockProgressReader is a mock of ProgressReader interface.
type MockProgressReader struct {
	ctrl     *gomock.Controller
	recorder *MockProgressReaderMockRecorder
}

// MockProgressReaderMockRecorder is the mock recorder for MockProgressReader.
type MockProgressReaderMockRecorder struct {
	mock *MockProgressReader
}

// NewMockProgressReader creates a new mock instance.
func NewMockProgressReader(ctrl *gomock.Controller) *MockProgressReader {
	mock := &MockProgressReader{ctrl: ctrl}
	mock.recorder = &MockProgressReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressReader) EXPECT() *MockProgressReaderMockRecorder {
	return m.recorder
}

// Progress mocks base method.
func (m *MockProgressReader) Progress(progress, total int64, units string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Progress", progress, total, units)
}

// Progress indicates an expected call of Progress.
func (mr *MockProgressReaderMockRecorder) Progress(progress, total, units interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockProgressReader)(nil).Progress), progress, total, units)
}

// Read mocks base method.
func (m *MockProgressReader) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockProgressReaderMockRecorder) Read(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockProgressReader)(nil).Read), p)
}

// MockProgressWriter is a mock of ProgressWriter interface.
type MockProgressWriter struct {
	ctrl     *gomock.Controller
	recorder *MockProgressWriterMockRecorder
}

// MockProgressWriterMockRecorder is the mock recorder for MockProgressWriter.
type MockProgressWriterMockRecorder struct {
	mock *MockProgressWriter
}

// NewMockProgressWriter creates a new mock instance.
func NewMockProgressWriter(ctrl *gomock.Controller) *MockProgressWriter {
	mock := &MockProgressWriter{ctrl: ctrl}
	mock.recorder = &MockProgressWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressWriter) EXPECT() *MockProgressWriterMockRecorder {
	return m.recorder
}

// Progress mocks base method.
func (m *MockProgressWriter) Progress(progress, total int64, units string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Progress", progress, total, units)
}

// Progress indicates an expected call of Progress.
func (mr *MockProgressWriterMockRecorder) Progress(progress, total, units interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Progress", reflect.TypeOf((*MockProgressWriter)(nil).Progress), progress, total, units)
}

// Write mocks base method.
func (m *MockProgressWriter) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockProgressWriterMockRecorder) Write(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockProgressWriter)(nil).Write), p)
}

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddPanicReport mocks base method.
func (m *MockManager) AddPanicReport(arg0 context.Context, arg1 debug.PanicReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPanicReport", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPanicReport indicates an expected call of AddPanicReport.
func (mr *MockManagerMockRecorder) AddPanicReport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPanicReport", reflect.TypeOf((*MockManager)(nil).AddPanicReport), arg0, arg1)
}

// Create mocks base method.
func (m *MockManager) Create(arg0 context.Context, arg1 Package) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockManagerMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManager)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockManager) Delete(arg0 context.Context, arg1 string, arg2 Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), arg0, arg1, arg2)
}

// DeletePackage mocks base method.
func (m *MockManager) DeletePackage(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePackage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePackage indicates an expected call of DeletePackage.
func (mr *MockManagerMockRecorder) DeletePackage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePackage", reflect.TypeOf((*MockManager)(nil).DeletePackage), arg0, arg1)
}

// DeletePanicReport mocks base method.
func (m *MockManager) DeletePanicReport(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePanicReport", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePanicReport indicates an expected call of DeletePanicReport.
func (mr *MockManagerMockRecorder) DeletePanicReport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePanicReport", reflect.TypeOf((*MockManager)(nil).DeletePanicReport), arg0, arg1)
}

// Get mocks base method.
func (m *MockManager) Get(arg0 context.Context, arg1 string, arg2 Version, arg3 ProgressWriter) (Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockManagerMockRecorder) Get(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockManager)(nil).Get), arg0, arg1, arg2, arg3)
}

// GetPackage mocks base method.
func (m *MockManager) GetPackage(arg0 context.Context, arg1 string) (Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackage", arg0, arg1)
	ret0, _ := ret[0].(Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackage indicates an expected call of GetPackage.
func (mr *MockManagerMockRecorder) GetPackage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackage", reflect.TypeOf((*MockManager)(nil).GetPackage), arg0, arg1)
}

// GetPanicReport mocks base method.
func (m *MockManager) GetPanicReport(arg0 context.Context, arg1 string) (debug.PanicReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPanicReport", arg0, arg1)
	ret0, _ := ret[0].(debug.PanicReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPanicReport indicates an expected call of GetPanicReport.
func (mr *MockManagerMockRecorder) GetPanicReport(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPanicReport", reflect.TypeOf((*MockManager)(nil).GetPanicReport), arg0, arg1)
}

// List mocks base method.
func (m *MockManager) List(arg0 context.Context, arg1 string, arg2 map[string]string) ([]Bundle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2)
	ret0, _ := ret[0].([]Bundle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockManagerMockRecorder) List(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManager)(nil).List), arg0, arg1, arg2)
}

// ListPackages mocks base method.
func (m *MockManager) ListPackages(arg0 context.Context, arg1 map[string]string) ([]Package, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPackages", arg0, arg1)
	ret0, _ := ret[0].([]Package)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPackages indicates an expected call of ListPackages.
func (mr *MockManagerMockRecorder) ListPackages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPackages", reflect.TypeOf((*MockManager)(nil).ListPackages), arg0, arg1)
}

// ListPanicReports mocks base method.
func (m *MockManager) ListPanicReports(ctx context.Context, pkg, ver string, filters map[string]string) ([]debug.PanicReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPanicReports", ctx, pkg, ver, filters)
	ret0, _ := ret[0].([]debug.PanicReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPanicReports indicates an expected call of ListPanicReports.
func (mr *MockManagerMockRecorder) ListPanicReports(ctx, pkg, ver, filters interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPanicReports", reflect.TypeOf((*MockManager)(nil).ListPanicReports), ctx, pkg, ver, filters)
}

// Upload mocks base method.
func (m *MockManager) Upload(arg0 context.Context, arg1 Bundle, arg2 ProgressReader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockManagerMockRecorder) Upload(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockManager)(nil).Upload), arg0, arg1, arg2)
}
