name: Test

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Test go ${{ matrix.go_version }} on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        go_version:
          # Test the two currently supported releases.
          # (https://go.dev/doc/devel/release#policy).
          - stable
          - oldstable

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./.../...

      - name: Build
        run: make debug

      - name: License
        run: make assert_license

      - name: Single Test
        run: make test GOTESTFLAGS="-timeout 240s"
